// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.9
// source: pkg/hoard.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hoard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hoard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_hoard_proto_rawDescGZIP(), []int{0}
}

type HoardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title  string  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Sender *Sender `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *HoardInfo) Reset() {
	*x = HoardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hoard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HoardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoardInfo) ProtoMessage() {}

func (x *HoardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hoard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoardInfo.ProtoReflect.Descriptor instead.
func (*HoardInfo) Descriptor() ([]byte, []int) {
	return file_pkg_hoard_proto_rawDescGZIP(), []int{1}
}

func (x *HoardInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HoardInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HoardInfo) GetSender() *Sender {
	if x != nil {
		return x.Sender
	}
	return nil
}

type Sender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Firstname string `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname  string `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
}

func (x *Sender) Reset() {
	*x = Sender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hoard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sender) ProtoMessage() {}

func (x *Sender) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hoard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sender.ProtoReflect.Descriptor instead.
func (*Sender) Descriptor() ([]byte, []int) {
	return file_pkg_hoard_proto_rawDescGZIP(), []int{2}
}

func (x *Sender) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *Sender) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hoard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hoard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_pkg_hoard_proto_rawDescGZIP(), []int{3}
}

func (x *Id) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_hoard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hoard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_pkg_hoard_proto_rawDescGZIP(), []int{4}
}

func (x *Status) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_pkg_hoard_proto protoreflect.FileDescriptor

var file_pkg_hoard_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x6b, 0x67, 0x2f, 0x68, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x57, 0x0a, 0x09, 0x48, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x42, 0x0a, 0x06, 0x53, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1a, 0x0a,
	0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xda, 0x01, 0x0a, 0x05, 0x48, 0x6f,
	0x61, 0x72, 0x64, 0x12, 0x2b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x61, 0x72, 0x64, 0x73,
	0x12, 0x0b, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f, 0x2e,
	0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x48, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x30, 0x01,
	0x12, 0x25, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x08, 0x2e, 0x6d,
	0x6f, 0x76, 0x65, 0x2e, 0x49, 0x64, 0x1a, 0x0f, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x48, 0x6f,
	0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x0f, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x48, 0x6f,
	0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x08, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x49,
	0x64, 0x12, 0x2c, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x61, 0x72, 0x64,
	0x12, 0x0f, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x48, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x0c, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x25, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x08,
	0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e, 0x49, 0x64, 0x1a, 0x0c, 0x2e, 0x6d, 0x6f, 0x76, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x3c, 0x0a, 0x12, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x61, 0x70, 0x70, 0x31, 0x2e, 0x68, 0x6f, 0x61, 0x72, 0x64, 0x42, 0x0a, 0x48, 0x6f,
	0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x12, 0x68, 0x6f, 0x61, 0x72,
	0x64, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6b, 0x67, 0xa2, 0x02,
	0x03, 0x4d, 0x41, 0x50, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_hoard_proto_rawDescOnce sync.Once
	file_pkg_hoard_proto_rawDescData = file_pkg_hoard_proto_rawDesc
)

func file_pkg_hoard_proto_rawDescGZIP() []byte {
	file_pkg_hoard_proto_rawDescOnce.Do(func() {
		file_pkg_hoard_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_hoard_proto_rawDescData)
	})
	return file_pkg_hoard_proto_rawDescData
}

var file_pkg_hoard_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_hoard_proto_goTypes = []interface{}{
	(*Empty)(nil),     // 0: move.Empty
	(*HoardInfo)(nil), // 1: move.HoardInfo
	(*Sender)(nil),    // 2: move.Sender
	(*Id)(nil),        // 3: move.Id
	(*Status)(nil),    // 4: move.Status
}
var file_pkg_hoard_proto_depIdxs = []int32{
	2, // 0: move.HoardInfo.sender:type_name -> move.Sender
	0, // 1: move.Hoard.GetHoards:input_type -> move.Empty
	3, // 2: move.Hoard.GetHoard:input_type -> move.Id
	1, // 3: move.Hoard.CreateHoard:input_type -> move.HoardInfo
	1, // 4: move.Hoard.UpdateHoard:input_type -> move.HoardInfo
	3, // 5: move.Hoard.DeleteHoard:input_type -> move.Id
	1, // 6: move.Hoard.GetHoards:output_type -> move.HoardInfo
	1, // 7: move.Hoard.GetHoard:output_type -> move.HoardInfo
	3, // 8: move.Hoard.CreateHoard:output_type -> move.Id
	4, // 9: move.Hoard.UpdateHoard:output_type -> move.Status
	4, // 10: move.Hoard.DeleteHoard:output_type -> move.Status
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_hoard_proto_init() }
func file_pkg_hoard_proto_init() {
	if File_pkg_hoard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_hoard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hoard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HoardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hoard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hoard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_hoard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_hoard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_hoard_proto_goTypes,
		DependencyIndexes: file_pkg_hoard_proto_depIdxs,
		MessageInfos:      file_pkg_hoard_proto_msgTypes,
	}.Build()
	File_pkg_hoard_proto = out.File
	file_pkg_hoard_proto_rawDesc = nil
	file_pkg_hoard_proto_goTypes = nil
	file_pkg_hoard_proto_depIdxs = nil
}
